export const ELEMENT_COLORS = [
  {
    name: "Indigo",
    value: "#6366f1",
    tailwind: "bg-indigo-500",
    border: "border-indigo-500",
    text: "text-indigo-400",
  },
  {
    name: "Red",
    value: "#ef4444",
    tailwind: "bg-red-500",
    border: "border-red-500",
    text: "text-red-400",
  },
  {
    name: "Orange",
    value: "#f97316",
    tailwind: "bg-orange-500",
    border: "border-orange-500",
    text: "text-orange-400",
  },
  {
    name: "Yellow",
    value: "#eab308",
    tailwind: "bg-yellow-500",
    border: "border-yellow-500",
    text: "text-yellow-400",
  },
  {
    name: "Green",
    value: "#22c55e",
    tailwind: "bg-green-500",
    border: "border-green-500",
    text: "text-green-400",
  },
  {
    name: "Blue",
    value: "#3b82f6",
    tailwind: "bg-blue-500",
    border: "border-blue-500",
    text: "text-blue-400",
  },
  {
    name: "Purple",
    value: "#a855f7",
    tailwind: "bg-purple-500",
    border: "border-purple-500",
    text: "text-purple-400",
  },
  {
    name: "Pink",
    value: "#ec4899",
    tailwind: "bg-pink-500",
    border: "border-pink-500",
    text: "text-pink-400",
  },
  {
    name: "Cyan",
    value: "#06b6d4",
    tailwind: "bg-cyan-500",
    border: "border-cyan-500",
    text: "text-cyan-400",
  },
  {
    name: "Teal",
    value: "#14b8a6",
    tailwind: "bg-teal-500",
    border: "border-teal-500",
    text: "text-teal-400",
  },
  {
    name: "Emerald",
    value: "#10b981",
    tailwind: "bg-emerald-500",
    border: "border-emerald-500",
    text: "text-emerald-400",
  },
  {
    name: "Lime",
    value: "#84cc16",
    tailwind: "bg-lime-500",
    border: "border-lime-500",
    text: "text-lime-400",
  },
  {
    name: "Fuchsia",
    value: "#d946ef",
    tailwind: "bg-fuchsia-500",
    border: "border-fuchsia-500",
    text: "text-fuchsia-400",
  },
  {
    name: "Rose",
    value: "#f43f5e",
    tailwind: "bg-rose-500",
    border: "border-rose-500",
    text: "text-rose-400",
  },
  {
    name: "Gray",
    value: "#71717a",
    tailwind: "bg-zinc-500",
    border: "border-zinc-500",
    text: "text-zinc-400",
  },
  {
    name: "White",
    value: "#fafafa",
    tailwind: "bg-zinc-50",
    border: "border-zinc-50",
    text: "text-zinc-50",
  },
];
